"""Fix autoincrement in pk_id fields

Revision ID: bd43bea51a8e
Revises: 2713deb1452c
Create Date: 2025-07-29 16:53:55.947725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd43bea51a8e'
down_revision: Union[str, Sequence[str], None] = '2713deb1452c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
